// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-fa0iH6IzNjUR9EqWOPpYu2FL6WRN56Q',
    appId: '1:290380500439:web:59d99225fb81cf64e64f92',
    messagingSenderId: '290380500439',
    projectId: 'fisilti-app-e85aa',
    authDomain: 'fisilti-app-e85aa.firebaseapp.com',
    storageBucket: 'fisilti-app-e85aa.firebasestorage.app',
    measurementId: 'G-JYM6XFFYE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpT8_nP4r7Cyb54VT7A0R3DGkbXONXOug',
    appId: '1:290380500439:android:b4e030f9ed1491e8e64f92',
    messagingSenderId: '290380500439',
    projectId: 'fisilti-app-e85aa',
    storageBucket: 'fisilti-app-e85aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHs-l78CsQvK6S9tvyII-UQwIR7mkD5WE',
    appId: '1:290380500439:ios:f2b21ee21986fad3e64f92',
    messagingSenderId: '290380500439',
    projectId: 'fisilti-app-e85aa',
    storageBucket: 'fisilti-app-e85aa.firebasestorage.app',
    iosBundleId: 'com.example.fisiltiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHs-l78CsQvK6S9tvyII-UQwIR7mkD5WE',
    appId: '1:290380500439:ios:f2b21ee21986fad3e64f92',
    messagingSenderId: '290380500439',
    projectId: 'fisilti-app-e85aa',
    storageBucket: 'fisilti-app-e85aa.firebasestorage.app',
    iosBundleId: 'com.example.fisiltiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-fa0iH6IzNjUR9EqWOPpYu2FL6WRN56Q',
    appId: '1:290380500439:web:13a3b06d45a1b801e64f92',
    messagingSenderId: '290380500439',
    projectId: 'fisilti-app-e85aa',
    authDomain: 'fisilti-app-e85aa.firebaseapp.com',
    storageBucket: 'fisilti-app-e85aa.firebasestorage.app',
    measurementId: 'G-KY0X4WBDBR',
  );
}
